# Generated by Django 4.0.5 on 2022-07-23 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='ProgrammableParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('pparameter1', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pparameter2', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pparameter3', models.DecimalField(decimal_places=4, max_digits=5)),
                ('parameter4', models.DecimalField(decimal_places=4, max_digits=5)),
                ('pparameter5', models.DecimalField(decimal_places=4, max_digits=5)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devices')),
            ],
        ),
    ]
